[output]
deny = ["unmaintained", "unsound", "yanked"]
quiet = false

[advisories]
ignore = [
    # Ignore because it doesn't apply to our protobuf crate
    "RUSTSEC-2024-0437",
    # Ignore advisory that bincode is unmaintained
    "RUSTSEC-2025-0141",
]
